import "./globals.css";
export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-segoe antialiased bg-gray-50 text-black">
        {children}
      </body>
    </html>
  );
}
